import LocalizedStrings from "react-localization"

export const strings = new LocalizedStrings({
  fi: {
    stations: "Asemat",
    journeys: "Matkat",
    search: "Etsi",
    coveredDistance: "Matkan pituus (km)",
    duration: "Kesto (min)",
    returnStationName: "Paluu asema",
    departureStationName : "Lähtö asema",
    departure: "Lähtö",
    return: "Palautus",
    capacity: "Kapasiteetti",
    name: "Nimi",
    address: "Osoite",
    countOfDepartures: "Lähtöjen määrä",
    countOfReturns: "Paluuten määrä",
    avDistanceDepartures: "Keskimääräinen lähtömatkan pituus",
    avDistanceReturns: "Keskimääräinen paluumatkan pituus",
    popularReturns: "Suositut paluuasemat",
    popularDepartures: "Suositut lähtöasemat",
    returnToList: "Takaisin listaukseen",
    may: "Toukokuu",
    june: "Kesäkuu",
    july: "Heinäkuu",
    all: "Kaikki",
    filter: "Suodata",
    close: "Sulje",
    empty: "Tyhjennä",
    days: "vrk",
    hours: "Tunnit",
    min: "Min",
    errors: {
      invalidInput: "Virheellinen syöte",
      tooSmallNumber: "Pienempi kuin minimi",
    }
  },
  gb: {
    stations: "Stations",
    journeys: "Journeys",
    search: "Search",
    coveredDistance: "The length of the journey (km)",
    duration: "Duration",
    returnStationName: "Return station",
    departureStationName: "Departure Station",
    departure: "Departure",
    return: "Return",
    capacity: "Capacity",
    name: "Name",
    address: "Address",
    countOfDepartures: "Count of departures",
    countOfReturns: "Count of returns",
    avDistanceDepartures: "Average distance of departures",
    avDistanceReturns: "Average distance of returns",
    popularReturns: "Popular returns",
    popularDepartures: "Popular departures",
    returnToList: "Return to list",
    may: "May",
    june: "June",
    july: "July",
    all: "All",
    filter: "Filter",
    close: "Close",
    empty: "Empty",
    days: "days",
    hours: "Hours",
    min: "Min",
    errors: {
      invalidInput: "Invalid input",
      tooSmallNumber: "Smaller than minimum",
    }
  },
  se: {
    stations: "Stationer",
    journeys: "Resor",
    search: "Sök",
    coveredDistance: "Resans längd (km)",
    duration: "Varaktighet",
    returnStationName: "Returstation",
    departureStationName: "Avgångsstation",
    departure: "Avresa",
    return: "Returnerad",
    capacity: "Kapacitet",
    name: "Namn",
    address: "Adress",
    countOfDepartures: "Antal avgångar",
    countOfReturns: "Antal returer",
    avDistanceDepartures: "Genomsnittligt avstånd av avgångar",
    avDistanceReturns: "Genomsnittligt avstånd av returer",
    popularReturns: "Populära returer",
    popularDepartures: "Populära avgångar",
    returnToList: "Återgå till listan",
    may: "Maj",
    june: "Juni",
    july: "Juli",
    all: "Allt",
    filter: "Filtrera",
    close: "Stäng",
    empty: "Tömma",
    days: "dagar",
    hours: "Timmar",
    min: "Minut",
    errors: {
      invalidInput: "Felaktig input",
      tooSmallNumber: "Mindre än minimum",
    }
    
  },
  empty: {
    stations: "",
    journeys: "",
    search: "",
    distance: "",
    duration: "",
    returnStationName: "",
    departureStationName: "",
    departure: "",
    return: "",
    capacity: "",
    name: "",
    address: "",
    countOfDepartures: "",
    countOfReturns: "",
    avDistanceDepartures: "",
    avDistanceReturns: "",
    popularReturns: "",
    popularDepartures: "",
    returnToList: "",
    may: "",
    june: "",
    july: "",
    all: "",
    filter: "",
    close: "",
    empty: "",
    days: "",
    hours: "",
    min: "",
    errors: {
      invalidInput: "",
      tooSmallNumber: "",
    }
  }
})