import LocalizedStrings from "react-localization"

export const strings = new LocalizedStrings({
  fi: {
    stations: "Asemat",
    journeys: "Matkat",
    search: "Etsi",
    coveredDistance: "Matkan pituus (km)",
    coveredDistanceM: "Matkan pituus (metrinä)",
    duration: "Kesto",
    durationSec: "Kesto (sekuntia)",
    returnStationName: "Paluu asema",
    departureStationName : "Lähtö asema",
    departure: "Lähtö",
    returntime: "Palautus",
    capacity: "Kapasiteetti",
    name: "Nimi",
    address: "Osoite",
    countOfDepartures: "Lähtöjen määrä",
    countOfReturns: "Paluuten määrä",
    avDistanceDepartures: "Keskimääräinen lähtömatkan pituus",
    avDistanceReturns: "Keskimääräinen paluumatkan pituus",
    popularReturns: "Suositut paluuasemat",
    popularDepartures: "Suositut lähtöasemat",
    returnToList: "Takaisin listaukseen",
    createNewJourney: "Luo uusi matka",
    createNewStation: "Luo uusi asema",
    newJourney: "Uusi matka",
    newStation: "Uusi asema",
    may: "Toukokuu",
    june: "Kesäkuu",
    july: "Heinäkuu",
    all: "Kaikki",
    filter: "Suodata",
    close: "Sulje",
    empty: "Tyhjennä",
    days: "vrk",
    hours: "Tunnit",
    min: "Min",
    format: "DD.MM.YYYY HH:mm:ss",
    dublicate: "löytyy jo ennestään",
    errors: {
      invalidInput: "Virheellinen syöte",
      tooSmallNumber: "Pienempi kuin minimi",
    },
    success: "Uudet tiedot lisätty onnistuneesti!",
    save: "tallenna"
  },
  gb: {
    stations: "Stations",
    journeys: "Journeys",
    search: "Search",
    coveredDistance: "The length of the journey (km)",
    coveredDistanceM: "The length of the journey (meter)",
    duration: "Duration",
    durationSec: "Duration (seconds)",
    returnStationName: "Return station",
    departureStationName: "Departure Station",
    departure: "Departure",
    returntime: "Return",
    capacity: "Capacity",
    name: "Name",
    address: "Address",
    countOfDepartures: "Count of departures",
    countOfReturns: "Count of returns",
    avDistanceDepartures: "Average distance of departures",
    avDistanceReturns: "Average distance of returns",
    popularReturns: "Popular returns",
    popularDepartures: "Popular departures",
    returnToList: "Return to list",
    createNewJourney: "Create new journey",
    createNewStation: "Create new station",
    newJourney: "New journey",
    newStation: "New Station",
    may: "May",
    june: "June",
    july: "July",
    all: "All",
    filter: "Filter",
    close: "Close",
    empty: "Empty",
    days: "days",
    hours: "Hours",
    min: "Min",
    format: "DD/MM/YYYY HH:mm:ss",
    dublicate: "can already be found",
    errors: {
      invalidInput: "Invalid input",
      tooSmallNumber: "Smaller than minimum",
    },
    success: "New information added successfully!",
    save: "Save"
  },
  se: {
    stations: "Stationer",
    journeys: "Resor",
    search: "Sök",
    coveredDistance: "Resans längd (km)",
    coveredDistanceM: "Resans längd (m)",
    duration: "Varaktighet",
    durationSec: "Varaktighet (sekunder)",
    returnStationName: "Returstation",
    departureStationName: "Avgångsstation",
    departure: "Avresa",
    returntime: "Returnerad",
    capacity: "Kapacitet",
    name: "Namn",
    address: "Adress",
    countOfDepartures: "Antal avgångar",
    countOfReturns: "Antal returer",
    avDistanceDepartures: "Genomsnittligt avstånd av avgångar",
    avDistanceReturns: "Genomsnittligt avstånd av returer",
    popularReturns: "Populära returer",
    popularDepartures: "Populära avgångar",
    returnToList: "Återgå till listan",
    createNewJourney: "Skapa ny resa",
    createNewStation: "Skapa ny station",
    newJourney: "Ny resa",
    newStation: "Ny station",
    may: "Maj",
    june: "Juni",
    july: "Juli",
    all: "Allt",
    filter: "Filtrera",
    close: "Stäng",
    empty: "Tömma",
    days: "dagar",
    hours: "Timmar",
    min: "Minut",
    format: "DD/MM/YYYY HH:mm:ss",
    dublicate: "kan redan hittas",
    errors: {
      invalidInput: "Felaktig input",
      tooSmallNumber: "Mindre än minimum",
    },
    success: "Ny information har lagts till!",
    save: "Spara"
  },
  empty: {
    stations: "",
    journeys: "",
    search: "",
    coveredDistance: "",
    coveredDistanceM: "",
    duration: "",
    durationSec: "",
    returnStationName: "",
    departureStationName: "",
    departure: "",
    returntime: "",
    capacity: "",
    name: "",
    address: "",
    countOfDepartures: "",
    countOfReturns: "",
    avDistanceDepartures: "",
    avDistanceReturns: "",
    popularReturns: "",
    popularDepartures: "",
    returnToList: "",
    createNewJourney: "",
    createNewStation: "",
    newJourney: "",
    newStation: "",
    may: "",
    june: "",
    july: "",
    all: "",
    filter: "",
    close: "",
    empty: "",
    days: "",
    hours: "",
    min: "",
    format: "",
    dublicate: "",
    errors: {
      invalidInput: "",
      tooSmallNumber: "",
    },
    success: "",
    save: ""
  }
})