import LocalizedStrings from "react-localization"

export const strings = new LocalizedStrings({
  fi: {
    stations: "Asemat",
    journeys: "Matkat",
    search: "Etsi",
    distanceCoverage: "Matkan pituus",
    duration: "Kesto",
    returnStation: "Paluu asema",
    departureStation: "Lähtö asema",
    departure: "Lähtö",
    return: "Palautus",
    capacity: "Kapasiteetti",
    name: "Nimi",
    address: "Osoite",
    countOfDepartures: "Lähtöjen määrä",
    countOfReturns: "Paluuten määrä",
    avDistanceDepartures: "Keskimääräinen lähtömatkan pituus",
    avDistanceReturns: "Keskimääräinen paluumatkan pituus",
    popularReturns: "Suositut paluuasemat",
    popularDepartures: "Suositut lähtöasemat",
    returnToList: "Takaisin listaukseen",
    may: "Toukokuu",
    june: "Kesäkuu",
    july: "Heinäkuu",
    all: "Kaikki",
  },
  gb: {
    stations: "Stations",
    journeys: "Journeys",
    search: "Search",
    distanceCoverage: "The length of the journey",
    duration: "Duration",
    returnStation: "Return station",
    departureStation: "Departure Station",
    departure: "Departure",
    return: "Return",
    capacity: "Capacity",
    name: "Name",
    address: "Address",
    countOfDepartures: "Count of departures",
    countOfReturns: "Count of returns",
    avDistanceDepartures: "Average distance of departures",
    avDistanceReturns: "Average distance of returns",
    popularReturns: "Popular returns",
    popularDepartures: "Popular departures",
    returnToList: "Return to list",
    may: "May",
    june: "June",
    july: "July",
    all: "All",
  },
  se: {
    stations: "Stationer",
    journeys: "Resor",
    search: "Sök",
    distanceCoverage: "Resans längd",
    duration: "Varaktighet",
    returnStation: "Returstation",
    departureStation: "Avgångsstation",
    departure: "Avresa",
    return: "Returnerad",
    capacity: "Kapacitet",
    name: "Namn",
    address: "Adress",
    countOfDepartures: "Antal avgångar",
    countOfReturns: "Antal returer",
    avDistanceDepartures: "Genomsnittligt avstånd av avgångar",
    avDistanceReturns: "Genomsnittligt avstånd av returer",
    popularReturns: "Populära returer",
    popularDepartures: "Populära avgångar",
    returnToList: "Återgå till listan",
    may: "Maj",
    june: "Juni",
    july: "Juli",
    all: "Allt",
  },
  empty: {
    stations: "",
    journeys: "",
    search: "",
    distance: "",
    duration: "",
    returnStation: "",
    departureStation: "",
    departure: "",
    return: "",
    capacity: "",
    name: "",
    address: "",
    countOfDepartures: "",
    countOfReturns: "",
    avDistanceDepartures: "",
    avDistanceReturns: "",
    popularReturns: "",
    popularDepartures: "",
    returnToList: "",
    may: "",
    june: "",
    july: "",
    all: "",
  }
})